#!/bin/bash
function killservice()
{   
    pgrep -x $1 > /dev/null 
    if [ $? -eq 0 ]
    then
        killall -9 -q $1 & > /dev/null
    fi
}
killservice 'restd';
killservice 'ipmi_module';
killservice 'memdbd';
killservice 'assetd';
killservice 'asset_module'
killservice 'redfishd';
killservice 'rmmlogd';
killservice 'registerd'
sudo ldconfig
ln -s /etc/init.d/rmm /etc/rcS.d/S101rmm
